language: go
go:
  - 1.11.x

os:
  - linux

dist: trusty
sudo: false

install: true

env:
  - GO111MODULE=on

script:
  - make build
  - make test
  - make coverage

after_success:
  - cp .coverage.out coverage.txt
  - bash <(curl -s https://codecov.io/bash)
